### PR TITLE
Fixed NPE in updateEndpoints when endpoints update event does not contain addresses array

### LINKED ISSUE #21: NullPointerException in KubeServiceState
### Version

5.0.1

### Context

Hi,

I'm getting NullPointerException in KubeServiceState. It seems that addresses list is sometimes not filled. My backends were overloaded when it appeared so possible case is that none of backend pods were in ready state. 

```
java.lang.NullPointerException: Cannot invoke "io.vertx.core.json.JsonArray.size()" because "addresses" is null
        at io.vertx.serviceresolver.kube.impl.KubeServiceState.handleEndpoints(KubeServiceState.java:108)
        at io.vertx.serviceresolver.kube.impl.KubeServiceState.handleUpdate(KubeServiceState.java:92)
        at io.vertx.serviceresolver.kube.impl.KubeServiceState.lambda$connectWebSocket$0(KubeServiceState.java:61)
        at io.vertx.core.internal.ContextInternal.dispatch(ContextInternal.java:249)
        at io.vertx.core.http.impl.WebSocketImplBase.receiveFrame(WebSocketImplBase.java:439)
        at io.vertx.core.http.impl.WebSocketImplBase$1.handleMessage(WebSocketImplBase.java:112)
        at io.vertx.core.http.impl.WebSocketImplBase$1.handleMessage(WebSocketImplBase.java:101)
        at io.vertx.core.internal.concurrent.InboundMessageQueue.test(InboundMessageQueue.java:86)
        at io.vertx.core.streams.impl.MessagePassingQueue.drain(MessagePassingQueue.java:228)
        at io.vertx.core.streams.impl.MessagePassingQueue.drain(MessagePassingQueue.java:210)
        at io.vertx.core.internal.concurrent.InboundMessageQueue.drainInternal(InboundMessageQueue.java:168)
        at io.vertx.core.internal.concurrent.InboundMessageQueue.drain(InboundMessageQueue.java:145)
        at io.vertx.core.internal.concurrent.InboundMessageQueue.write(InboundMessageQueue.java:132)
        at io.vertx.core.http.impl.WebSocketImplBase.handleFrame(WebSocketImplBase.java:373)
        at io.vertx.core.http.impl.WebSocketConnectionImpl.handleWsFrame(WebSocketConnectionImpl.java:197)
        at io.vertx.core.http.impl.WebSocketConnectionImpl.handleMessage(WebSocketConnectionImpl.java:176)
        at io.vertx.core.net.impl.VertxConnection.read(VertxConnection.java:247)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1537)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1395)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1446)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1429)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:167)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.handle(AbstractNioChannel.java:445)
        at io.netty.channel.nio.NioIoHandler$DefaultNioRegistration.handle(NioIoHandler.java:381)
        at io.netty.channel.nio.NioIoHandler.processSelectedKey(NioIoHandler.java:575)
        at io.netty.channel.nio.NioIoHandler.processSelectedKeysOptimized(NioIoHandler.java:550)
        at io.netty.channel.nio.NioIoHandler.processSelectedKeys(NioIoHandler.java:491)
        at io.netty.channel.nio.NioIoHandler.run(NioIoHandler.java:468)
        at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:206)
        at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:177)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to reproduce

_No response_

### Do you have a reproducer?

_No response_

### PR DESCRIPTION
**Pull request by MichalKoziorowski-TomTom**
Fixes #21

Motivation:

I've got modification event from K8S without addresses array filled and just with notReadyAddresses:
```
{
  "type": "MODIFIED",
  "object": {
    "kind": "Endpoints",
    "apiVersion": "v1",
    "metadata": {
      "name": "frontend-1",
      "namespace": "api",
      "uid": "f7ddf126-e06c-4b8c-a401-5e17b163ac50",
      "resourceVersion": "27159",
      "creationTimestamp": "2025-10-30T12:18:36Z",
      "labels": {
        "app": "routing-api",
        "id": "1",
        "instance": "frontend-1",
        "name": "frontend"
      },
      "managedFields": [
        {
          "manager": "kube-controller-manager",
          "operation": "Update",
          "apiVersion": "v1",
          "time": "2025-10-30T13:03:17Z",
          "fieldsType": "FieldsV1",
          "fieldsV1": {
            "f:metadata": {
              "f:labels": {
                ".": {},
                "f:app": {},
                "f:id": {},
                "f:instance": {},
                "f:name": {}
              }
            },
            "f:subsets": {}
          }
        }
      ]
    },
    "subsets": [
      {
        "notReadyAddresses": [
          {
            "ip": "10.240.0.234",
            "nodeName": "aks-nkwpool-18983291-vmss000006",
            "targetRef": {
              "kind": "Pod",
              "namespace": "api",
              "name": "nkw-service-deployment-1-69d55c55b8-sgvml",
              "uid": "824bca44-2883-443b-b2d4-98c535c26f81"
            }
          }
        ],
        "ports": [
          {
            "name": "http",
            "port": 6599,
            "protocol": "TCP"
          }
        ]
      }
    ]
  }
}
```

Conformance:

You should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

File: src/main/java/io/vertx/serviceresolver/kube/impl/KubeServiceState.java [hunk 1]
```diff
@@ -64,10 +64,12 @@ void updateEndpoints(JsonObject item) {
           JsonObject subset = subsets.getJsonObject(j);
           JsonArray addresses = subset.getJsonArray("addresses");
           JsonArray ports = subset.getJsonArray("ports");
-          for (int k = 0;k < addresses.size();k++) {
-            JsonObject address = addresses.getJsonObject(k);
-            String ip = address.getString("ip");
-            podIps.add(ip);
+          if (addresses != null) {
```
Comment (vietj) [inline src/main/java/io/vertx/serviceresolver/kube/impl/KubeServiceState.java]: can you add a comment explaining the motivation for this ?

Comment (vietj) [reply src/main/java/io/vertx/serviceresolver/kube/impl/KubeServiceState.java:69]: nope that's just me lingering

**Comment by vietj** [comment]
@MichalKoziorowski-TomTom can you provide a 5.0 backport PR ?
